###
POST http://localhost:8080/admin/user/
Content-Type: application/json
Authorization: Basic admin:admin

{
    "username": "power_admin",
    "firstName": "Mid",
    "lastName": "Admin",
    "enabled": true,
    "password": "admin",
    "roles": [
        "ROLE_USER",
        "ROLE_POWER_USER"
    ]
}

###
GET http://localhost:8080/admin/user/admin
Content-Type: application/json
Authorization: Basic admin:admin

###
DELETE  http://localhost:8080/admin/user/admin
Content-Type: application/json
Authorization: Basic admin:admin

###
GET  http://localhost:8080/oauth2/token?grant_type=client_credentials
Authorization: Basic admin:admin
Content-Type: application/json

###
GET http://localhost:8080/public/user/admin/reset-password

###
POST http://localhost:8080/public/change-password/
Content-Type: application/json

{
    "requestKey": "9N4BwP9wWzBQMRYTHjAk2ZuKbKDPqtsJUWs9QU6mI4w=",
    "newPassword": "admin"
}