plugins {
    id 'java'
    id 'io.freefair.lombok' version "8.6"
}

version = '1.0.0-SNAPSHOT'
layout.buildDirectory = file("$projectDir/build")
group = 'com.akbo.auth'

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'
    apply plugin: 'io.freefair.lombok'
    apply plugin: 'jacoco'

    layout.buildDirectory = file("$projectDir/build")

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    checkstyle {
        toolVersion = '10.12.5'
        configFile = rootProject.file('config/checkstyle/checkstyle.xml')
        ignoreFailures = false
        showViolations = true
    }

    jacoco {
        toolVersion = "0.8.12"
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.3'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.3'
    }

    test {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            html.required = true
        }
    }
}
