plugins {
    id 'java'
    id 'io.freefair.lombok' version "8.6"
}

version = '1.0.0-SNAPSHOT'
layout.buildDirectory = file("$projectDir/build")
group = 'com.akbo.auth'

allprojects {
    repositories {
        maven() {
            url = uri("https://plugins.gradle.org/m2/")
        }
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'io.freefair.lombok'
    layout.buildDirectory = file("$projectDir/build")

    // Use Java 21 toolchain across all modules
    apply plugin: 'java'
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}


dependencies {

}

