spring:
  security:
    client:
      secret: password
      salt: ABCDEFGHIJKLMOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
    user:
      name: user
      password: password
    oauth2:
      resource-owner:
        jwt:
          signing-key: secret
app:
  auth:
    issuer: http://localhost:8080
    client-id: albedo-client
    client-secret: albedo-secret
    client-scopes: openid,profile,read,write
    client-redirect-uri: http://127.0.0.1:8080/login/oauth2/code/albedo-client
    access-token-ttl: PT1H
    refresh-token-ttl: PT12H

logging:
  level:
    org.springframework.security: trace
